#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/itel/P13001L

PRODUCT_COPY_FILES += \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/Himax_firmware.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/Himax_firmware.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/focaltech_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/focaltech_ts_fw.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6781v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6781v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6785v96.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6785v96.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6785v99.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6785v99.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6853v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6853v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6873v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6873v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6877v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6877v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6885v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6885v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6885v1.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6885v1.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6885v9c.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6885v9c.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_6893v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_6893v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_90hz6785.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_90hz6785.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_90hz6877.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_90hz6877.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_90hz6885.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_90hz6885.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_cfg_gt9885v1.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_cfg_gt9885v1.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6781v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6781v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6785a4.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6785a4.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6785ae.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6785ae.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6853v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6853v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6873v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6873v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6877af.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6877af.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6877v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6877v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6885a1.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6885a1.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6885af.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6885af.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6885b0.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6885b0.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6885b1.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6885b1.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6885v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6885v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9886_firmware_6893v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9886_firmware_6893v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6781v01_1080x2280.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6781v01_1080x2300.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6789v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6789v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6833v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6833v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6853v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6853v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6855v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6855v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6873v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6873v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6877v01_1080x2280.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6877v01_1080x2300.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6879v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6879v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6893v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6893v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6893v02.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6893v02.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6893v03.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6893v03.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6893v04.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6893v04.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6893v05.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6893v05.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6895v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6895v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_cfg_6983v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_cfg_6983v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6781v01_1080x2280.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6781v01_1080x2300.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6789v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6789v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6833v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6833v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6853v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6853v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6855v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6855v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6873v00.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6873v00.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6877v01_1080x2280.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6877v01_1080x2300.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6879v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6879v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6893v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6893v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6893v02.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6893v02.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6893v03.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6893v03.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6893v04.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6893v04.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6893v05.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6893v05.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6895v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6895v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/gt9896s_firmware_6983v01.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/gt9896s_firmware_6983v01.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_144.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_144.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_jdi.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_jdi.bin \
    vendor/itel/P13001L/proprietary/recovery/root/vendor/firmware/novatek_ts_fw_tm.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/novatek_ts_fw_tm.bin \
    vendor/itel/P13001L/proprietary/vendor/app/t6/02662e8e-e126-11e5-b86d9a79f06e9478.ta:$(TARGET_COPY_OUT_VENDOR)/app/t6/02662e8e-e126-11e5-b86d9a79f06e9478.ta \
    vendor/itel/P13001L/proprietary/vendor/app/t6/9ef77781-7bd5-4e39-965f20f6f211f400.ta:$(TARGET_COPY_OUT_VENDOR)/app/t6/9ef77781-7bd5-4e39-965f20f6f211f400.ta \
    vendor/itel/P13001L/proprietary/vendor/app/t6/b46325e6-5c90-8252-2eada8e32e5180d6.ta:$(TARGET_COPY_OUT_VENDOR)/app/t6/b46325e6-5c90-8252-2eada8e32e5180d6.ta \
    vendor/itel/P13001L/proprietary/vendor/app/t6/cfg.ini:$(TARGET_COPY_OUT_VENDOR)/app/t6/cfg.ini \
    vendor/itel/P13001L/proprietary/vendor/app/t6/data/E62563B4905C52822EADA8E32E5180D6/6B6579626F785F6372797074:$(TARGET_COPY_OUT_VENDOR)/app/t6/data/E62563B4905C52822EADA8E32E5180D6/6B6579626F785F6372797074 \
    vendor/itel/P13001L/proprietary/vendor/app/t6/face1d41-2636-11e1-ad9e0002a5d6c51b.ta:$(TARGET_COPY_OUT_VENDOR)/app/t6/face1d41-2636-11e1-ad9e0002a5d6c51b.ta \
    vendor/itel/P13001L/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/fstb.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/fstb.cfg \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.1-service-mediatek.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.security.keymint-service.trustkernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.trustkernel.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.thermal@2.0-service.mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.thermal@2.0-service.mtk.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/android.hardware.usb@1.2-service-mediatekv2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb@1.2-service-mediatekv2.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/bootperf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/bootperf.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/chipinfo_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/chipinfo_init.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/hw/init.aee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.aee.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/hw/init.connectivity.common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.common.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/hw/init.connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/hw/init.modem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.modem.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/hw/init.mtkgki.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mtkgki.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/hw/init.project.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.project.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/hw/init.sensor_2_0.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.sensor_2_0.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/hw/init_connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init_connectivity.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.bip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.bip_ap.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip_ap.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.cccifsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccifsd.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.fpsgo.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fpsgo.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.gps_pwr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_pwr.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.thermal_core.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_core.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.wfca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wfca.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/lbs_hidl_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lbs_hidl_service.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/trustkernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustkernel.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkpower@1.0-init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkpower@1.0-init.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/vendor.mediatek.hardware.mtkpower@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mtkpower@1.0-service.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/volte_clientapi_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_clientapi_ua.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootCA.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootCA.crt \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG2.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG2.crt \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG3.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG3.crt \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/EntrustRootCertificationAuthorityG2_root.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/EntrustRootCertificationAuthorityG2_root.crt \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GlobalSign_root_CA.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GlobalSign_root_CA.crt \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/LibertyGlobalEnterprise-Root-CA-G1.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/LibertyGlobalEnterprise-Root-CA-G1.crt \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root-R3.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Root-R3.cer \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/USERTrustRSACertificationAuthority.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/USERTrustRSACertificationAuthority.crt \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/gold.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/gold.cer \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/thawte.der \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/ssl/openssl.cnf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ssl/openssl.cnf \
    vendor/itel/P13001L/proprietary/vendor/etc/ipsec/strongswan.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/strongswan.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/meow.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/meow.cfg \
    vendor/itel/P13001L/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/itel/P13001L/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/itel/P13001L/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/itel/P13001L/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/01419da9.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/01419da9.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/04f60c28.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/04f60c28.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/0d69c7e1.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/0d69c7e1.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/10531352.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/10531352.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/111e6273.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/111e6273.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/12d55845.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/12d55845.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/1ae85e5e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1ae85e5e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/1df5a75f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1df5a75f.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/1e1eab7c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1e1eab7c.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/1e8e7201.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1e8e7201.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/1eb37bdf.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1eb37bdf.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/1f58a078.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1f58a078.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/219d9499.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/219d9499.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/23f4c490.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/23f4c490.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/27af790d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/27af790d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/2add47b6.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/2add47b6.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/2d9dafe4.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/2d9dafe4.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/2fa87019.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/2fa87019.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/302904dd.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/302904dd.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/304d27c3.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/304d27c3.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/31188b5e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/31188b5e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/33ee480d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/33ee480d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/343eb6cb.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/343eb6cb.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/35105088.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/35105088.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/399e7759.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/399e7759.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/3ad48a91.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3ad48a91.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/3c6676aa.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3c6676aa.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/3c860d51.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3c860d51.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/3c899c73.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3c899c73.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/3c9a4d3b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3c9a4d3b.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/3e7271e8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3e7271e8.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/40dc992e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/40dc992e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/455f1b52.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/455f1b52.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/48a195d8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/48a195d8.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/4be590e0.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/4be590e0.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/5046c355.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5046c355.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/524d9b43.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/524d9b43.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/52b525c7.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/52b525c7.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/583d0756.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/583d0756.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/5a250ea7.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5a250ea7.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/5a3f0ff8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5a3f0ff8.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/5acf816d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5acf816d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/5cf9d536.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5cf9d536.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/5f47b495.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5f47b495.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/60afe812.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/60afe812.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/6187b673.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/6187b673.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/63a2c897.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/63a2c897.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/69105f4f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/69105f4f.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/6b03dec0.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/6b03dec0.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/75680d2e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/75680d2e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/76579174.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/76579174.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/7892ad52.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/7892ad52.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/7a7c655d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/7a7c655d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/7a819ef2.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/7a819ef2.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/81b9768f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/81b9768f.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/82223c44.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/82223c44.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/83e9984f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/83e9984f.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/85cde254.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/85cde254.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/86212b19.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/86212b19.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/869fbf79.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/869fbf79.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/882de061.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/882de061.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/88950faa.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/88950faa.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/89c02a45.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/89c02a45.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/8d6437c3.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/8d6437c3.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9282e51c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9282e51c.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9339512a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9339512a.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9479c8c3.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9479c8c3.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9576d26b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9576d26b.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9591a472.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9591a472.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/95aff9e3.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/95aff9e3.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9685a493.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9685a493.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/985c1f52.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/985c1f52.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9aef356c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9aef356c.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9d6523ce.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9d6523ce.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/9f533518.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9f533518.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/a2c66da8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a2c66da8.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/a3896b44.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a3896b44.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/a7605362.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a7605362.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/a81e292b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a81e292b.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/a9d40e02.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a9d40e02.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/ab5346f4.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/ab5346f4.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/ab59055e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/ab59055e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/aeb67534.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/aeb67534.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/b0ed035a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b0ed035a.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/b0f3e76e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b0f3e76e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/b3fb433b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b3fb433b.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/b74d2bd5.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b74d2bd5.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/b7db1890.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b7db1890.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/b872f2b4.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b872f2b4.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/b936d1c6.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b936d1c6.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/bc3f2570.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/bc3f2570.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/bd43e1dd.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/bd43e1dd.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/bdacca6f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/bdacca6f.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/bf64f35b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/bf64f35b.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/c491639e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/c491639e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/c51c224c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/c51c224c.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/c559d742.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/c559d742.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/c90bc37d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/c90bc37d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/cb1c3204.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/cb1c3204.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/ccc52f49.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/ccc52f49.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/cf701eeb.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/cf701eeb.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/d06393bb.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d06393bb.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/d16a5865.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d16a5865.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/d18e9066.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d18e9066.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/d39b0a2c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d39b0a2c.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/d41b5e2a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d41b5e2a.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/d4c339cb.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d4c339cb.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/d59297b8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d59297b8.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/d7746a63.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d7746a63.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/da7377f6.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/da7377f6.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/dbc54cab.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/dbc54cab.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/dbff3a01.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/dbff3a01.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/dc99f41e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/dc99f41e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/dfc0fe80.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/dfc0fe80.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/e442e424.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/e442e424.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/e48193cf.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/e48193cf.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/e8651083.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/e8651083.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/ed39abd0.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/ed39abd0.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/edcbddb5.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/edcbddb5.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/f013ecaf.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/f013ecaf.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/f0cd152c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/f0cd152c.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/f459871d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/f459871d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/fb5fa911.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/fb5fa911.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/fd08c599.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/fd08c599.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts/fde84897.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/fde84897.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/111e6273.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/111e6273.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/3ad48a91.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/3ad48a91.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/7651b327.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/7651b327.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/c542733d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/c542733d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/f336e3d1.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/f336e3d1.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/18dc3a8d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/18dc3a8d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/1bc5ca0c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/1bc5ca0c.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/1bc5ca0c.1:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/1bc5ca0c.1 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/2cbfcc3a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/2cbfcc3a.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/35ef1c14.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/35ef1c14.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/399e7759.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/399e7759.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/586933d9.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/586933d9.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/6146415b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/6146415b.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/66272d0d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/66272d0d.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/6f1dbe5e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/6f1dbe5e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/b5805141.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/b5805141.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/b805b58a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/b805b58a.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/ed7b215e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/ed7b215e.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/security/cacerts_supl/lab/ef4b31e6.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/ef4b31e6.0 \
    vendor/itel/P13001L/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/itel/P13001L/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/disable_skin_control.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_skin_control.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/disable_thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/disable_thermal_temp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal_temp.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/disable_throttling.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_throttling.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/thermal_mtbf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_mtbf.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/thermal_policy_00.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_00.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/thermal_policy_02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_02.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/thermal/thermal_policy_08.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_08.conf \
    vendor/itel/P13001L/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/itel/P13001L/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/itel/P13001L/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/itel/P13001L/proprietary/vendor/firmware/Himax_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/itel/P13001L/proprietary/vendor/firmware/WMT_SOC_CO_CLK.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC_CO_CLK.cfg \
    vendor/itel/P13001L/proprietary/vendor/firmware/aw87xxx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_acf.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/itel/P13001L/proprietary/vendor/firmware/focaltech_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6781v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6781v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6785v96.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6785v96.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6785v99.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6785v99.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6853v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6873v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6877v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6877v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6885v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6885v1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v1.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6885v9c.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6885v9c.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_6893v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_90hz6785.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_90hz6785.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_90hz6877.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_90hz6877.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_90hz6885.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_90hz6885.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_cfg_gt9885v1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_cfg_gt9885v1.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6781v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6781v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6785a4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6785a4.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6785ae.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6785ae.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6853v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6873v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6877af.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6877af.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6877v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6877v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6885a1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885a1.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6885af.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885af.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6885b0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885b0.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6885b1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885b1.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6885v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6885v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9886_firmware_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9886_firmware_6893v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6781v01_1080x2280.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6781v01_1080x2300.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6789v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6789v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6833v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6833v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6853v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6855v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6855v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6873v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6873v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6877v01_1080x2280.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6877v01_1080x2300.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6879v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6879v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6893v02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v02.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6893v03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v03.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6893v04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v04.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6893v05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6893v05.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6895v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6895v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_cfg_6983v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_cfg_6983v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6781v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6781v01_1080x2280.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6781v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6781v01_1080x2300.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6789v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6789v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6833v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6833v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6853v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6853v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6855v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6855v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6873v00.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6873v00.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6877v01_1080x2280.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6877v01_1080x2280.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6877v01_1080x2300.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6877v01_1080x2300.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6879v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6879v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6893v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6893v02.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v02.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6893v03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v03.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6893v04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v04.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6893v05.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6893v05.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6895v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6895v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/gt9896s_firmware_6983v01.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gt9896s_firmware_6983v01.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6627_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_v1_coeff.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6627_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6627_fm_v1_patch.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6630_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v1_coeff.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6630_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v1_patch.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6630_fm_v2_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_coeff.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6630_fm_v2_coeff_tx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_coeff_tx.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6630_fm_v2_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_patch.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6630_fm_v2_patch_tx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6630_fm_v2_patch_tx.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6632_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6632_fm_v1_coeff.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6632_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6632_fm_v1_patch.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6635_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_coeff.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/mt6635_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6635_fm_v1_patch.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/novatek_ts_fw_144.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_144.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/novatek_ts_fw_jdi.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_jdi.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/novatek_ts_fw_tm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_fw_tm.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/itel/P13001L/proprietary/vendor/firmware/soc2_2_ram_bt_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1d_1_hdr.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/soc2_2_ram_bt_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1e_1_hdr.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/soc2_2_ram_mcu_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1d_1_hdr.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/soc2_2_ram_mcu_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1e_1_hdr.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/soc2_2_ram_wifi_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1d_1_hdr.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/soc2_2_ram_wifi_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1e_1_hdr.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/soc_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_coeff.bin \
    vendor/itel/P13001L/proprietary/vendor/firmware/soc_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc_fm_v1_patch.bin \
    vendor/itel/P13001L/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg

PRODUCT_PACKAGES += \
    AVCSecureVdecCA \
    HEVCSecureVdecCA \
    VP9SecureVdecCA \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    libAVCSecureVencCA \
    libaedv \
    libbwc \
    libgz_gp_client \
    libgz_uree \
    libhevce_sb.ca7.android \
    libion_mtk \
    libion_ulit \
    libipsec_ims_shr \
    libladder \
    libmtkcutils \
    libmtkperf_client_vendor \
    libmtkproperty \
    libmtkrillog \
    libpowerhalwrap_vendor \
    libthha \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libverno \
    libwo \
    libmtk_drvb \
    vendor.mediatek.hardware.videotelephony@1.0_vendor \
    libHEVCdec_sa.ca7.android \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libh264enc_sa.ca7 \
    libmp4enc_sa.ca7 \
    libmp4enc_xa.ca7 \
    librcs_volte_core \
    libvcodec_utility_plat.mt6789 \
    libvolte_core_shr \
    libvolte_xdmc_shr \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvcodec_utility \
    libvcodec_utility_v3a \
    libvcodecdrv \
    libvcodecdrv_v3a \
    libvpudv3a_vcodec \
    vendor.mediatek.hardware.rcs@2.0 \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    android.hardware.security.keymint-V3-ndk-mtk \
    libGLES_meow \
    libMEOW_data \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    gc08a3_mipi_raw_tuning \
    gc5035f_mipi_raw_tuning \
    hi1333_mipi_raw_IdxMgr \
    hi1333_mipi_raw_tuning \
    android.hardware.bluetooth@1.1-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.thermal@2.0-impl \
    audio.primary.mediatek \
    audio.r_submix.mediatek \
    gatekeeper.trustkernel \
    gps.default \
    hwcomposer.mtk_common \
    kmsetkey.trustkernel \
    libSoftGatekeeper \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gralloc.common \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.1-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vulkan.mali \
    sensors.mediatek.V2.0 \
    sound_trigger.primary.default \
    thermal_hal \
    vendor.mediatek.hardware.bluetooth.audio@2.2-impl \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.mtkpower@1.2-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    lbs_hidl_service-impl \
    libCamera_gc08a3mipiraw_E2EHDR_Preview \
    libCamera_gc08a3mipiraw_E2EHDR_Video \
    libCamera_gc08a3mipiraw_Face_Capture \
    libCamera_gc08a3mipiraw_Flash_Capture \
    libCamera_gc08a3mipiraw_HDR_Capture \
    libCamera_gc08a3mipiraw_HDR_Preview \
    libCamera_gc08a3mipiraw_HDR_Reconfig_Preview \
    libCamera_gc08a3mipiraw_HDR_Reconfig_Video \
    libCamera_gc08a3mipiraw_HDR_Video \
    libCamera_gc08a3mipiraw_N3D_Capture \
    libCamera_gc08a3mipiraw_N3D_Preview \
    libCamera_gc08a3mipiraw_N3D_Video \
    libCamera_gc08a3mipiraw_P1_YUV \
    libCamera_gc08a3mipiraw_Scene_Capture \
    libCamera_gc08a3mipiraw_Scene_Capture_4cell \
    libCamera_gc08a3mipiraw_Scene_Preview \
    libCamera_gc08a3mipiraw_Scene_Preview_4k \
    libCamera_gc08a3mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_gc08a3mipiraw_Video_1080 \
    libCamera_gc08a3mipiraw_Video_4k \
    libCamera_gc5035fmipiraw_E2EHDR_Preview \
    libCamera_gc5035fmipiraw_E2EHDR_Video \
    libCamera_gc5035fmipiraw_Face_Capture \
    libCamera_gc5035fmipiraw_Flash_Capture \
    libCamera_gc5035fmipiraw_HDR_Capture \
    libCamera_gc5035fmipiraw_HDR_Preview \
    libCamera_gc5035fmipiraw_HDR_Reconfig_Preview \
    libCamera_gc5035fmipiraw_HDR_Reconfig_Video \
    libCamera_gc5035fmipiraw_HDR_Video \
    libCamera_gc5035fmipiraw_N3D_Capture \
    libCamera_gc5035fmipiraw_N3D_Preview \
    libCamera_gc5035fmipiraw_N3D_Video \
    libCamera_gc5035fmipiraw_P1_YUV \
    libCamera_gc5035fmipiraw_Scene_Capture \
    libCamera_gc5035fmipiraw_Scene_Capture_4cell \
    libCamera_gc5035fmipiraw_Scene_Preview \
    libCamera_gc5035fmipiraw_Scene_Preview_4k \
    libCamera_gc5035fmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_gc5035fmipiraw_Video_1080 \
    libCamera_gc5035fmipiraw_Video_4k \
    libCamera_hi1333mipiraw_E2EHDR_Preview \
    libCamera_hi1333mipiraw_E2EHDR_Video \
    libCamera_hi1333mipiraw_Face_Capture \
    libCamera_hi1333mipiraw_Flash_Capture \
    libCamera_hi1333mipiraw_HDR_Capture \
    libCamera_hi1333mipiraw_HDR_Preview \
    libCamera_hi1333mipiraw_HDR_Reconfig_Preview \
    libCamera_hi1333mipiraw_HDR_Reconfig_Video \
    libCamera_hi1333mipiraw_HDR_Video \
    libCamera_hi1333mipiraw_N3D_Capture \
    libCamera_hi1333mipiraw_N3D_Preview \
    libCamera_hi1333mipiraw_N3D_Video \
    libCamera_hi1333mipiraw_P1_YUV \
    libCamera_hi1333mipiraw_Scene_Capture \
    libCamera_hi1333mipiraw_Scene_Capture_4cell \
    libCamera_hi1333mipiraw_Scene_Preview \
    libCamera_hi1333mipiraw_Scene_Preview_4k \
    libCamera_hi1333mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_hi1333mipiraw_Video_1080 \
    libCamera_hi1333mipiraw_Video_4k \
    libCamera_s5k4hayxmipiraw_E2EHDR_Preview \
    libCamera_s5k4hayxmipiraw_E2EHDR_Video \
    libCamera_s5k4hayxmipiraw_Face_Capture \
    libCamera_s5k4hayxmipiraw_Flash_Capture \
    libCamera_s5k4hayxmipiraw_HDR_Capture \
    libCamera_s5k4hayxmipiraw_HDR_Preview \
    libCamera_s5k4hayxmipiraw_HDR_Reconfig_Preview \
    libCamera_s5k4hayxmipiraw_HDR_Reconfig_Video \
    libCamera_s5k4hayxmipiraw_HDR_Video \
    libCamera_s5k4hayxmipiraw_N3D_Capture \
    libCamera_s5k4hayxmipiraw_N3D_Preview \
    libCamera_s5k4hayxmipiraw_N3D_Video \
    libCamera_s5k4hayxmipiraw_P1_YUV \
    libCamera_s5k4hayxmipiraw_Scene_Capture \
    libCamera_s5k4hayxmipiraw_Scene_Capture_4cell \
    libCamera_s5k4hayxmipiraw_Scene_Preview \
    libCamera_s5k4hayxmipiraw_Scene_Preview_4k \
    libCamera_s5k4hayxmipiraw_Scene_Preview_ZSD_Flash \
    libCamera_s5k4hayxmipiraw_Video_1080 \
    libCamera_s5k4hayxmipiraw_Video_4k \
    libJpgEncPipe \
    libMtkSpeechEnh \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libTEECommon \
    lib_iir \
    lib_speech_enh \
    libaal_key \
    libaal_mtk \
    libalsautils-v31 \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiosmartpamtk \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_audio_session_mediatek \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbt-vendor \
    libcam.seninfn3d \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.lmv \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.utility \
    libcamalgo.warp \
    libcares_naptr \
    libcarrierconfig \
    libccci_util \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libcvsd_mtk \
    libfgauge_gm30 \
    libfile_op \
    libforkexecwrap \
    libformatter \
    libged \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgwsd-ril \
    libheichal \
    libhfmanager \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimgsensorca \
    libispcameraca \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkphhelper \
    libkphproxy \
    libksensor \
    libmipc \
    libmmagent \
    libmml \
    libmnetlink_v104 \
    libmsbc_mtk \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkares \
    libmtkcam_pipelinepolicy-aov \
    libmtkconfig \
    libmtkconfigutils \
    libmtkhardware_legacy \
    libmtkisp_metadata \
    libmtklimiter_vendor \
    libmtkmipc-ril \
    libmtknetcap \
    libmtknetutils \
    libmtkrilutils \
    libmtkshifter_vendor \
    libmtksysutils \
    libmtktinyxml \
    libmtkutils \
    libmvpu_cic_ci_compiler \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_engine \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_pub \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libneuron_graph_delegate.mtk \
    libneuron_platform \
    libnir_neon_driver_ndk.mtk.vndk \
    libnpagent \
    libnpagent_server \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    libperfctl_vendor \
    libpl \
    libpower_timer \
    libpowerhal \
    libpqframework \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librilfusion \
    librpc \
    librt_extamp_intf \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstorage_otp \
    libsysenv \
    libteec \
    libtflite_mtk \
    libtrm \
    libudf \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libvow_ap_test_aa \
    libvow_ap_test_dd \
    libvow_ap_test_ha \
    libvow_ap_test_hh \
    libvow_ap_test_nn \
    libvpu \
    libvpu5 \
    libwifi-hal-mtk \
    libwifitest \
    libwpfa \
    libwvhidl \
    libwvdrmengine \
    arm.graphics-V1-ndk_platform \
    bf2257l_mipi_raw_IdxMgr \
    gc08a3_mipi_raw_IdxMgr \
    gc5035f_mipi_raw_IdxMgr \
    imx214_mipi_raw_IdxMgr \
    imx214_mipi_raw_tuning \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_imx214mipiraw_E2EHDR_Preview \
    libCamera_imx214mipiraw_E2EHDR_Video \
    libCamera_imx214mipiraw_Face_Capture \
    libCamera_imx214mipiraw_Flash_Capture \
    libCamera_imx214mipiraw_HDR_Capture \
    libCamera_imx214mipiraw_HDR_Preview \
    libCamera_imx214mipiraw_HDR_Reconfig_Preview \
    libCamera_imx214mipiraw_HDR_Reconfig_Video \
    libCamera_imx214mipiraw_HDR_Video \
    libCamera_imx214mipiraw_N3D_Capture \
    libCamera_imx214mipiraw_N3D_Preview \
    libCamera_imx214mipiraw_N3D_Video \
    libCamera_imx214mipiraw_P1_YUV \
    libCamera_imx214mipiraw_Scene_Capture \
    libCamera_imx214mipiraw_Scene_Capture_4cell \
    libCamera_imx214mipiraw_Scene_Preview \
    libCamera_imx214mipiraw_Scene_Preview_4k \
    libCamera_imx214mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx214mipiraw_Video_1080 \
    libCamera_imx214mipiraw_Video_4k \
    libCamera_ov8858mipiraw_E2EHDR_Preview \
    libCamera_ov8858mipiraw_E2EHDR_Video \
    libCamera_ov8858mipiraw_Face_Capture \
    libCamera_ov8858mipiraw_Flash_Capture \
    libCamera_ov8858mipiraw_HDR_Capture \
    libCamera_ov8858mipiraw_HDR_Preview \
    libCamera_ov8858mipiraw_HDR_Reconfig_Preview \
    libCamera_ov8858mipiraw_HDR_Reconfig_Video \
    libCamera_ov8858mipiraw_HDR_Video \
    libCamera_ov8858mipiraw_N3D_Capture \
    libCamera_ov8858mipiraw_N3D_Preview \
    libCamera_ov8858mipiraw_N3D_Video \
    libCamera_ov8858mipiraw_P1_YUV \
    libCamera_ov8858mipiraw_Scene_Capture \
    libCamera_ov8858mipiraw_Scene_Capture_4cell \
    libCamera_ov8858mipiraw_Scene_Preview \
    libCamera_ov8858mipiraw_Scene_Preview_4k \
    libCamera_ov8858mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_ov8858mipiraw_Video_1080 \
    libCamera_ov8858mipiraw_Video_4k \
    libDR \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust_func \
    libaalservice \
    libaiawb_moon \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaibc_tuning_p4 \
    libaidepth_tuning \
    libaiselector \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.ispfeature \
    libcamalgo.lsc \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.vsf \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libdip_drv \
    libdip_postproc \
    libdpframework \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libgpudataproducer \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    liblpcnr \
    libmnl \
    libmsnr \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libneuron_runtime.5 \
    libnir_neon_driver \
    libpq_cust_base \
    libpq_prot \
    libpqparamparser \
    libstereoinfoaccessor_vsdof \
    ov8858_mipi_raw_IdxMgr \
    ov8858_mipi_raw_tuning \
    s5k4hayx_mipi_raw_IdxMgr \
    libmtkcam_streaminfo_plugin-p1stt \
    s5k4hayx_mipi_raw_tuning \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.clientapi@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.lbs@1.0 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    libem_support_jni \
    EngineerMode \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.keymint-service.trustkernel.xml \
    android.hardware.security.secureclock-service.trustkernel.xml \
    android.hardware.security.sharedsecret-service.trustkernel.xml \
    android.hardware.usb@1.2-service-mediatekv2.xml \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    lbs_hidl_service@1.0.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_apuware_apusys.xml \
    manifest_apuware_hmp.xml \
    manifest_apuware_utils.xml \
    manifest_cameraprovider.xml \
    manifest_hwcomposer.xml \
    manifest_media_c2_V1_2_default.xml \
    bip \
    bip_ap \
    ccci_mdinit \
    ccci_rpcd \
    chipinfo \
    epdg_wod \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.security.keymint-service.trustkernel \
    android.hardware.thermal@2.0-service.mtk \
    android.hardware.usb@1.2-service-mediatekv2 \
    android.hardware.graphics.allocator@4.0-service-mediatek.mt6789 \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.mtkpower@1.0-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vtservice_hidl \
    init.insmod \
    ipsec_mon \
    lbs_hidl_service \
    mnld \
    v3avpud.mt6789 \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    rcs_volte_stack \
    tee_check_keybox \
    teed \
    thermal_core \
    volte_clientapi_ua \
    volte_imcb \
    volte_imsm_93 \
    volte_md_status \
    volte_rcs_ua \
    volte_stack \
    volte_ua \
    wfca \
    wlan_assistant \
    wmt_launcher \
    wmt_loader

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_graphics_allocator@4_0-service-mediatek \
    vendor_bin_hw_camerahalserver \
    vendor_bin_v3avpud \
    vendor_lib_libmtk_drvb_so \
    vendor_lib_libvcodec_utility_so \
    vendor_lib_libvcodec_utility_v3a_so \
    vendor_lib_libvcodecdrv_so \
    vendor_lib_libvcodecdrv_v3a_so \
    vendor_lib_libvpudv3a_vcodec_so \
    vendor_lib64_egl_libGLES_mali_so \
    vendor_lib64_hw_audio_primary_mt6789_so \
    vendor_lib64_hw_audio_r_submix_mt6789_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_hw_android_hardware_camera_provider@2_6-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_allocator@4_0-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib64_hw_gralloc_common_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_atms@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_bgservice@1_1-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_ccap@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_isphal@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_isphal@1_1-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_lomoeffect@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_pq@2_15-impl_so \
    vendor_lib64_hw_vulkan_mali_so \
    vendor_lib64_hw_sensors_mt6789_so \
    vendor_lib64_arm_graphics-V1-ndk_platform_so \
    vendor_lib64_bf2257l_mipi_raw_IdxMgr_so \
    vendor_lib64_gc08a3_mipi_raw_IdxMgr_so \
    vendor_lib64_gc5035f_mipi_raw_IdxMgr_so \
    vendor_lib64_imx214_mipi_raw_IdxMgr_so \
    vendor_lib64_imx214_mipi_raw_tuning_so \
    vendor_lib64_lib3a_ae_core_so \
    vendor_lib64_lib3a_ae_so \
    vendor_lib64_lib3a_ae_stat_so \
    vendor_lib64_lib3a_af_assist_so \
    vendor_lib64_lib3a_af_assist_utils_so \
    vendor_lib64_lib3a_af_core_so \
    vendor_lib64_lib3a_af_so \
    vendor_lib64_lib3a_alsflicker_so \
    vendor_lib64_lib3a_awb_core_so \
    vendor_lib64_lib3a_ccudrv_so \
    vendor_lib64_lib3a_ccuif_so \
    vendor_lib64_lib3a_custom_ae_so \
    vendor_lib64_lib3a_dce_so \
    vendor_lib64_lib3a_flash_so \
    vendor_lib64_lib3a_flicker_so \
    vendor_lib64_lib3a_gma_so \
    vendor_lib64_lib3a_lce_so \
    vendor_lib64_lib3a_log_so \
    vendor_lib64_lib3a_n3d3a_so \
    vendor_lib64_lib3a_sensors_color_so \
    vendor_lib64_lib3a_sensors_flicker_so \
    vendor_lib64_libCamera_imx214mipiraw_E2EHDR_Preview_so \
    vendor_lib64_libCamera_imx214mipiraw_E2EHDR_Video_so \
    vendor_lib64_libCamera_imx214mipiraw_Face_Capture_so \
    vendor_lib64_libCamera_imx214mipiraw_Flash_Capture_so \
    vendor_lib64_libCamera_imx214mipiraw_HDR_Capture_so \
    vendor_lib64_libCamera_imx214mipiraw_HDR_Preview_so \
    vendor_lib64_libCamera_imx214mipiraw_HDR_Reconfig_Preview_so \
    vendor_lib64_libCamera_imx214mipiraw_HDR_Reconfig_Video_so \
    vendor_lib64_libCamera_imx214mipiraw_HDR_Video_so \
    vendor_lib64_libCamera_imx214mipiraw_N3D_Capture_so \
    vendor_lib64_libCamera_imx214mipiraw_N3D_Preview_so \
    vendor_lib64_libCamera_imx214mipiraw_N3D_Video_so \
    vendor_lib64_libCamera_imx214mipiraw_P1_YUV_so \
    vendor_lib64_libCamera_imx214mipiraw_Scene_Capture_so \
    vendor_lib64_libCamera_imx214mipiraw_Scene_Capture_4cell_so \
    vendor_lib64_libCamera_imx214mipiraw_Scene_Preview_so \
    vendor_lib64_libCamera_imx214mipiraw_Scene_Preview_4k_so \
    vendor_lib64_libCamera_imx214mipiraw_Scene_Preview_ZSD_Flash_so \
    vendor_lib64_libCamera_imx214mipiraw_Video_1080_so \
    vendor_lib64_libCamera_imx214mipiraw_Video_4k_so \
    vendor_lib64_libCamera_ov8858mipiraw_E2EHDR_Preview_so \
    vendor_lib64_libCamera_ov8858mipiraw_E2EHDR_Video_so \
    vendor_lib64_libCamera_ov8858mipiraw_Face_Capture_so \
    vendor_lib64_libCamera_ov8858mipiraw_Flash_Capture_so \
    vendor_lib64_libCamera_ov8858mipiraw_HDR_Capture_so \
    vendor_lib64_libCamera_ov8858mipiraw_HDR_Preview_so \
    vendor_lib64_libCamera_ov8858mipiraw_HDR_Reconfig_Preview_so \
    vendor_lib64_libCamera_ov8858mipiraw_HDR_Reconfig_Video_so \
    vendor_lib64_libCamera_ov8858mipiraw_HDR_Video_so \
    vendor_lib64_libCamera_ov8858mipiraw_N3D_Capture_so \
    vendor_lib64_libCamera_ov8858mipiraw_N3D_Preview_so \
    vendor_lib64_libCamera_ov8858mipiraw_N3D_Video_so \
    vendor_lib64_libCamera_ov8858mipiraw_P1_YUV_so \
    vendor_lib64_libCamera_ov8858mipiraw_Scene_Capture_so \
    vendor_lib64_libCamera_ov8858mipiraw_Scene_Capture_4cell_so \
    vendor_lib64_libCamera_ov8858mipiraw_Scene_Preview_so \
    vendor_lib64_libCamera_ov8858mipiraw_Scene_Preview_4k_so \
    vendor_lib64_libCamera_ov8858mipiraw_Scene_Preview_ZSD_Flash_so \
    vendor_lib64_libCamera_ov8858mipiraw_Video_1080_so \
    vendor_lib64_libCamera_ov8858mipiraw_Video_4k_so \
    vendor_lib64_libDR_so \
    vendor_lib64_libSonyIMX230PdafLibrary_so \
    vendor_lib64_libSonyIMX230PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX338PdafLibrary_so \
    vendor_lib64_libSonyIMX338PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX386PdafLibrary_so \
    vendor_lib64_libSonyIMX386PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX519PdafLibrary_so \
    vendor_lib64_libSonyIMX519PdafLibraryWrapper_so \
    vendor_lib64_libaaa_ltm_so \
    vendor_lib64_libaaa_ltmx_so \
    vendor_lib64_libaal_cust_func_so \
    vendor_lib64_libaalservice_so \
    vendor_lib64_libaiawb_moon_so \
    vendor_lib64_libaiawb_p1ggm_so \
    vendor_lib64_libaiawb_sun_so \
    vendor_lib64_libaibc_tuning_so \
    vendor_lib64_libaibc_tuning_p2_so \
    vendor_lib64_libaibc_tuning_p3_so \
    vendor_lib64_libaibc_tuning_p4_so \
    vendor_lib64_libaidepth_tuning_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libcam_afhal_so \
    vendor_lib64_libcam_chdr_so \
    vendor_lib64_libcam_feature_utils_so \
    vendor_lib64_libcam_hal3a_cctsvr_so \
    vendor_lib64_libcam_hal3a_log_so \
    vendor_lib64_libcam_hal3a_v3_ae_so \
    vendor_lib64_libcam_hal3a_v3_ai3a_so \
    vendor_lib64_libcam_hal3a_v3_awb_so \
    vendor_lib64_libcam_hal3a_v3_dng_so \
    vendor_lib64_libcam_hal3a_v3_fsmgr_so \
    vendor_lib64_libcam_hal3a_v3_lscMgr_so \
    vendor_lib64_libcam_hal3a_v3_lsctbl_50_so \
    vendor_lib64_libcam_hal3a_v3_nvram_50_so \
    vendor_lib64_libcam_hal3a_v3_platform_so \
    vendor_lib64_libcam_hal3a_v3_resultpool_so \
    vendor_lib64_libcam_hal3a_v3_so \
    vendor_lib64_libcam_halisp_buf_so \
    vendor_lib64_libcam_halisp_common_so \
    vendor_lib64_libcam_halisp_so \
    vendor_lib64_libcam_halsensor_hwintegration_so \
    vendor_lib64_libcam_halsensor_so \
    vendor_lib64_libcam_iopipe_so \
    vendor_lib64_libcam_isptuning_so \
    vendor_lib64_libcam_pdtblgen_so \
    vendor_lib64_libcam_tuning_cache_so \
    vendor_lib64_libcam_utils_sensorprovider_so \
    vendor_lib64_libcam_vhdr_so \
    vendor_lib64_libcamalgo_ispfeature_so \
    vendor_lib64_libcamalgo_lsc_so \
    vendor_lib64_libcamalgo_platform2_so \
    vendor_lib64_libcamalgo_rotate_so \
    vendor_lib64_libcamalgo_vsf_so \
    vendor_lib64_libcamdrv_isp_so \
    vendor_lib64_libcamdrv_tuning_mgr_so \
    vendor_lib64_libcamdrv_twin_so \
    vendor_lib64_libcamera_custom_pd_buf_mgr_so \
    vendor_lib64_libcamera_customae_so \
    vendor_lib64_libcamera_customaf_so \
    vendor_lib64_libcamera_customawb_so \
    vendor_lib64_libcamera_customflk_so \
    vendor_lib64_libcameracustom_camera_3a_so \
    vendor_lib64_libcameracustom_camera_isp_so \
    vendor_lib64_libcameracustom_camera_sensors_so \
    vendor_lib64_libcameracustom_camera_exif_so \
    vendor_lib64_libcameracustom_eis_so \
    vendor_lib64_libcameracustom_flashlight_so \
    vendor_lib64_libcameracustom_lens_so \
    vendor_lib64_libcameracustom_plugin_so \
    vendor_lib64_libcameracustom_so \
    vendor_lib64_libdip_drv_so \
    vendor_lib64_libdip_postproc_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libeffecthal_base_so \
    vendor_lib64_libfeature_face_so \
    vendor_lib64_libfeature_stereo_provider_so \
    vendor_lib64_libfeature_vsdof_hal_so \
    vendor_lib64_libfeature_3dnr_so \
    vendor_lib64_libfeature_eis_so \
    vendor_lib64_libfeature_fsc_so \
    vendor_lib64_libfeature_lmv_so \
    vendor_lib64_libfeature_rss_so \
    vendor_lib64_libfeatureiodrv_mem_so \
    vendor_lib64_libgpudataproducer_so \
    vendor_lib64_libimageio_so \
    vendor_lib64_libimageio_plat_drv_so \
    vendor_lib64_libimageio_plat_pipe_so \
    vendor_lib64_liblpcnr_so \
    vendor_lib64_libmnl_so \
    vendor_lib64_libmsnr_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libmtkcam_atmseventmgr_so \
    vendor_lib64_libmtkcam_eventcallback_so \
    vendor_lib64_libmtkcam_featurepipe_capture_so \
    vendor_lib64_libmtkcam_featurepipe_depthmap_so \
    vendor_lib64_libmtkcam_featurepipe_streaming_so \
    vendor_lib64_libmtkcam_featurepipe_vsdof_util_so \
    vendor_lib64_libmtkcam_logicalmodule_so \
    vendor_lib64_libmtkcam_3rdparty_core_so \
    vendor_lib64_libmtkcam_3rdparty_customer_so \
    vendor_lib64_libmtkcam_3rdparty_mtk_so \
    vendor_lib64_libmtkcam_3rdparty_so \
    vendor_lib64_libmtkcam_calibration_convertor_so \
    vendor_lib64_libmtkcam_calibration_provider_so \
    vendor_lib64_libmtkcam_debugutils_so \
    vendor_lib64_libmtkcam_device3_app_so \
    vendor_lib64_libmtkcam_device3_hal_so \
    vendor_lib64_libmtkcam_device3_hidl_so \
    vendor_lib64_libmtkcam_device3_hidlutils_so \
    vendor_lib64_libmtkcam_device3_utils_so \
    vendor_lib64_libmtkcam_devicesessionpolicy_so \
    vendor_lib64_libmtkcam_diputils_so \
    vendor_lib64_libmtkcam_exif_so \
    vendor_lib64_libmtkcam_fdvt_so \
    vendor_lib64_libmtkcam_featurepolicy_so \
    vendor_lib64_libmtkcam_featureutils_so \
    vendor_lib64_libmtkcam_fwkutils_so \
    vendor_lib64_libmtkcam_grallocutils_so \
    vendor_lib64_libmtkcam_hwnode_so \
    vendor_lib64_libmtkcam_hwutils_so \
    vendor_lib64_libmtkcam_imem_so \
    vendor_lib64_libmtkcam_imgbuf_so \
    vendor_lib64_libmtkcam_mapping_mgr_so \
    vendor_lib64_libmtkcam_metadata_so \
    vendor_lib64_libmtkcam_metastore_so \
    vendor_lib64_libmtkcam_mfb_so \
    vendor_lib64_libmtkcam_modulefactory_aaa_so \
    vendor_lib64_libmtkcam_modulefactory_custom_so \
    vendor_lib64_libmtkcam_modulefactory_drv_so \
    vendor_lib64_libmtkcam_modulefactory_utils_so \
    vendor_lib64_libmtkcam_modulehelper_so \
    vendor_lib64_libmtkcam_owe_so \
    vendor_lib64_libmtkcam_pipeline_so \
    vendor_lib64_libmtkcam_pipeline_fbm_so \
    vendor_lib64_libmtkcam_pipelinemodel_so \
    vendor_lib64_libmtkcam_pipelinemodel_adapter_so \
    vendor_lib64_libmtkcam_pipelinemodel_capture_so \
    vendor_lib64_libmtkcam_pipelinemodel_isp_so \
    vendor_lib64_libmtkcam_pipelinemodel_session_so \
    vendor_lib64_libmtkcam_pipelinemodel_utils_so \
    vendor_lib64_libmtkcam_pipelinemodel_zsl_so \
    vendor_lib64_libmtkcam_pipelinepolicy-security_so \
    vendor_lib64_libmtkcam_pipelinepolicy-smvr_so \
    vendor_lib64_libmtkcam_pipelinepolicy_so \
    vendor_lib64_libmtkcam_pipelinepolicy_factory_so \
    vendor_lib64_libmtkcam_prerelease_so \
    vendor_lib64_libmtkcam_rsc_so \
    vendor_lib64_libmtkcam_scenariorecorder_so \
    vendor_lib64_libmtkcam_stdutils_so \
    vendor_lib64_libmtkcam_streamutils_so \
    vendor_lib64_libmtkcam_synchelper_so \
    vendor_lib64_libmtkcam_sysutils_so \
    vendor_lib64_libmtkcam_tuning_utils_so \
    vendor_lib64_libmtkcam_ulog_so \
    vendor_lib64_libneuralnetworks_sl_driver_mtk_prebuilt_so \
    vendor_lib64_libneuron_adapter_mgvi_so \
    vendor_lib64_libneuron_runtime_5_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_cust_base_so \
    vendor_lib64_libpq_prot_so \
    vendor_lib64_libpqparamparser_so \
    vendor_lib64_libstereoinfoaccessor_vsdof_so \
    vendor_lib64_ov8858_mipi_raw_IdxMgr_so \
    vendor_lib64_ov8858_mipi_raw_tuning_so \
    vendor_lib64_s5k4hayx_mipi_raw_IdxMgr_so \
    vendor_lib64_mtkcam_libmtkcam_streaminfo_plugin-p1stt_so
